apiVersion: v1
kind: Service
metadata:
  name: marron-vert # nom du service
  namespace: blog
#  le lb par defaut est classic lb
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: marron-vert
  type: LoadBalancer
  ports:
    - name: port1 
      protocol: TCP
      port: 80
      targetPort: 80
